<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Table;
class Database extends Model
{
    protected $table = 'remote_databases';

    public  static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

    public function remoteTable()
    {

        return $this->hasMany(\App\Models\Table::class,'database_id','id');
    }
}
